#!/usr/bin/env bash
#
# vnext.sh — stage Vigil to vigil.bible/vnext/, verify it, then promote it.
#
#   ./vnext.sh stage     mirror the working index.html into vnext/, push it
#   ./vnext.sh promote   publish the verified build to the root of the site
#   ./vnext.sh status    what is staged, what is live, what differs
#   ./vnext.sh serve     serve root and vnext/ locally on one origin
#
# There is ONE hand-edited copy of this app and it is ./index.html.
# vnext/ is GENERATED — never edit it. `promote` re-generates and compares,
# so a hand-edit there fails loudly instead of quietly becoming the drift
# that a second copy of a single-file app always threatens to become.
#
set -euo pipefail
cd "$(dirname "$0")"

DIR=vnext
MIRROR=(index.html sw.js manifest.webmanifest
        icon-192.png icon-512.png icon-maskable-512.png apple-touch-icon.png)
# CNAME is deliberately absent: it is Pages configuration and is only ever
# valid at the root of the site.

say(){ printf '\033[2m%s\033[0m\n' "$*"; }
die(){ printf '\033[31m%s\033[0m\n' "$*" >&2; exit 1; }

# Build a deployment of the app into $1. The rewrites are kept to the
# absolute minimum on purpose: a preview you have altered is a preview you
# have not verified. Only deployment metadata changes — never the app.
generate(){
  local dest=$1
  mkdir -p "$dest"
  for f in "${MIRROR[@]}"; do cp -p "$f" "$dest/$f"; done

  python3 - "$dest" <<'PY'
import io, json, sys, re
dest = sys.argv[1]

BANNER = ("<!-- GENERATED by vnext.sh from the index.html at the root of this "
          "repo. Do not edit: ./vnext.sh promote regenerates and compares, and "
          "any hand-edit here fails that check. -->\n")

p = dest + "/index.html"
s = io.open(p, encoding="utf-8").read()
# noindex, because a preview of a Bible is exactly the sort of thing a
# search engine is delighted to index twice.
s = s.replace("<head>", '<head>\n<meta name="robots" content="noindex,nofollow">', 1)
io.open(p, "w", encoding="utf-8").write(BANNER + s)

# A distinguishable name, so an installed preview and the real app are not
# two identical icons on the same home screen. start_url already differs,
# so the two install as separate apps.
p = dest + "/manifest.webmanifest"
m = json.load(io.open(p, encoding="utf-8"))
m["name"] = "Vigil Next"
m["short_name"] = "Vigil Next"
m["description"] = "Preview build. The real one is at vigil.bible."
io.open(p, "w", encoding="utf-8").write(json.dumps(m, indent=2) + "\n")
PY
}

# Everything the site needs in order to keep the preview out of the index.
write_robots(){
  cat > robots.txt <<'ROBOTS'
User-agent: *
Disallow: /vnext/
ROBOTS
}

case "${1:-}" in

stage)
  generate "$DIR"
  write_robots
  git add "$DIR" robots.txt
  if git diff --cached --quiet; then
    say "vnext/ already matches index.html — nothing to stage."
    exit 0
  fi
  git diff --cached --stat
  read -rp $'\nPush this to vigil.bible/vnext/ ? [y/N] ' ok
  [[ "$ok" == [yY]* ]] || die "Stopped. Nothing pushed."
  git commit -qm "Stage a build to vnext/ for verification"
  git push -q
  say "Staged. Verify at https://vigil.bible/vnext/"
  say "Settings -> About shows the build and the scope it is serving."
  ;;

promote)
  tmp=$(mktemp -d); trap 'rm -rf "$tmp"' EXIT
  generate "$tmp/$DIR"
  # The point of the whole exercise: what you verified must be what ships.
  if ! diff -rq "$tmp/$DIR" "$DIR" >/dev/null 2>&1; then
    diff -rq "$tmp/$DIR" "$DIR" || true
    die $'\nvnext/ is not what index.html would produce right now.\nEither index.html changed since you staged (run: ./vnext.sh stage),\nor vnext/ was edited by hand (it is generated — edit index.html).'
  fi
  git add "${MIRROR[@]}"
  if git diff --cached --quiet; then
    say "Root already matches the verified build. Nothing to promote."
    exit 0
  fi
  git diff --cached --stat
  read -rp $'\nPromote this to vigil.bible ? [y/N] ' ok
  [[ "$ok" == [yY]* ]] || die "Stopped. Nothing promoted."
  git commit -qm "Promote verified vnext build to the site root"
  git push -q
  say "Live at https://vigil.bible"
  say "Remember: the launch that notices a new sw.js is still served the OLD"
  say "HTML. Settings -> About -> Update now to skip the wait."
  ;;

status)
  tmp=$(mktemp -d); trap 'rm -rf "$tmp"' EXIT
  generate "$tmp/$DIR"
  if [[ ! -d "$DIR" ]]; then
    say "Nothing staged yet — run: ./vnext.sh stage"
  elif diff -rq "$tmp/$DIR" "$DIR" >/dev/null 2>&1; then
    say "vnext/ matches the current index.html."
  else
    printf '\033[33m%s\033[0m\n' "vnext/ is STALE or hand-edited:"
    diff -rq "$tmp/$DIR" "$DIR" || true
  fi
  echo
  say "Uncommitted at the root:"
  git status --short "${MIRROR[@]}" || true
  ;;

serve)
  port=${2:-8080}
  generate "$DIR"
  say "Root    http://localhost:$port/"
  say "Preview http://localhost:$port/$DIR/"
  say "One origin, as on the real site — so this is where storage and cache"
  say "isolation is actually testable. Ctrl-C to stop."
  python3 -m http.server "$port"
  ;;

*)
  sed -n '2,14p' "$0" | sed 's/^# \{0,1\}//'
  exit 1
  ;;
esac
